name: File Actions

on:
  push:
    branches: [main]

jobs:
  file_actions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Crear carpeta
      run: mkdir Carpeta_nueva
    
    - name: Create file
      run: touch Carpeta_nueva/example.txt
      
    - name: Agregar archivo a la carpeta
      run: cp archivo_ejemplo.txt Carpeta_nueva/
      



